gui:
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --paging=never
customCommands:
  - key: 'I'
    command: "gh issue list"
    context: 'global'
    subprocess: true
    description: "Issue aperte"
