gui:
  showIcons: true
git:
  pagers:
    - pager: delta --dark --paging=never
    - externalDiffCommand: difft --color=always
customCommands:
  - key: 'I'
    command: "gh issue list"
    context: 'global'
    description: "Issue aperte"
    output: terminal
  - key: 'C'
    command: "git diff --cached | opencode run 'Write a concise git commit message for these changes'"
    context: 'files'
    description: "Generate commit message with Opencode"
    loadingText: "Generating commit message..."
    output: terminal
