gui:
  showIcons: true
git:
  pagers:
    - pager: delta --dark --paging=never
    - externalDiffCommand: difft --color=always
customCommands:
  - key: 'I'
    command: "gh issue list"
    context: 'global'
    description: "Issue aperte"
    output: terminal
