gui:
  showIcons: true
  theme:
    activeBorderColor:
      - "#31748f"
      - bold

    inactiveBorderColor:
      - "#6e6a86"

    searchingActiveBorderColor:
      - "#ebbcba"
      - bold

    optionsTextColor:
      - "#9ccfd8"

    selectedLineBgColor:
      - "#31748f"

    inactiveViewSelectedLineBgColor:
      - "#26233a"
      - bold

    cherryPickedCommitFgColor:
      - "#1f1d2e"

    cherryPickedCommitBgColor:
      - "#ebbcba"

    markedBaseCommitFgColor:
      - "#9ccfd8"

    markedBaseCommitBgColor:
      - "#f6c177"

    unstagedChangesColor:
      - "#eb6f92"

    defaultFgColor:
      - "#e0def4"
git:
  pagers:
    - pager: delta --paging=never
    - externalDiffCommand: difft --color=always
customCommands:
  - key: 'I'
    command: "gh issue list"
    context: 'global'
    description: "Issue aperte"
    output: terminal
  - key: 'C'
    command: "git diff --cached | opencode run 'Write a concise git commit message for these changes'"
    context: 'files'
    description: "Generate commit message with Opencode"
    loadingText: "Generating commit message..."
    output: terminal
